# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100)),
                ('chat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbr', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0.0)),
                ('paidby', models.CharField(default='Unspecified', max_length=100)),
                ('purpose', models.CharField(default='Unspecified', max_length=100)),
                ('currency', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='flock.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(default='Unspecified', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('budget', models.IntegerField(blank=True, default=0.0)),
                ('budget_currency', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='flock.Currency')),
                ('chat', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='flock.Chat')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('timezone', models.CharField(default=None, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='track',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='flock.Track'),
        ),
        migrations.AddField(
            model_name='bill',
            name='expense',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='flock.Expense'),
        ),
    ]
