# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0002_auto_20170402_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='purpose',
            field=models.CharField(default='Unspecified', max_length=100),
        ),
    ]
