# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0002_remove_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
