# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0003_track_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='paidby',
            field=models.CharField(default='Unspecified', max_length=100),
        ),
    ]
