# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0004_auto_20170402_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupMember',
        ),
    ]
