# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0007_auto_20170403_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='track',
            name='budget_currency',
        ),
    ]
