# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flock', '0009_auto_20170403_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=100)),
                ('expense', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='flock.Expense')),
            ],
        ),
    ]
