# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flockapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattrack',
            name='purpose',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
