# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flockapp', '0002_chattrack_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatexpense',
            name='paidby',
        ),
        migrations.AddField(
            model_name='chatexpense',
            name='paidbywhom',
            field=models.CharField(default='none', max_length=30),
        ),
    ]
