# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flockapp', '0002_auto_20170215_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='flockapp.User'),
        ),
        migrations.AlterField(
            model_name='track',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
