# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flockapp', '0003_auto_20170215_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
