# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flockapp', '0004_modelwithimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelWithImage',
            new_name='Bills',
        ),
    ]
